# Atelier NumPy 

**Contexte :** Une entreprise dispose de capteurs installés dans plusieurs bâtiments. Ces capteurs mesurent la température, l'humidité, la pression et la consommation énergétique. On va préparer et analyser ces données avec NumPy, avant qu'elles soient utilisées par un futur système de Machine Learning.

Chaque partie contient :
- une **explication** en français simple,
- le **code** à exécuter,
- parfois une **question de réflexion**.

On commence par importer NumPy.
C'est la bibliothèque Python spécialisée dans le calcul scientifique et les tableaux de nombres . on l'utilise presque toujours avec le surnom `np`.

In [2]:
import numpy as np

---
## Partie 1 : Listes Python vs tableaux NumPy

**Objectif:**

 Avant d'utiliser NumPy, il faut comprendre *pourquoi* on l'utilise plutôt que les listes Python classiques. Les deux permettent de stocker plusieurs valeurs, mais elles ne se comportent pas du tout pareil face aux opérations mathématiques.

On dispose des températures mesurées par un capteur : `24.5, 25.1, 26.3, 27.0, 25.8`

### 1) Créer une liste Python stockant ces températures

Une **liste Python** est une structure générique : elle peut contenir n'importe quel type de données mélangées (nombres, texte, etc.). On la crée avec des crochets `[ ]`.

In [6]:
temperatures_list = [24.5, 25.1, 26.3, 27.0, 25.8 ]
print(temperatures_list)

[24.5, 25.1, 26.3, 27.0, 25.8]


### 2) Créer un tableau NumPy équivalent

Un **tableau NumPy** (`ndarray`) est optimisé pour les calculs numériques : toutes les valeurs sont du même type, stockées de façon compacte en mémoire, ce qui rend les calculs beaucoup plus rapides. On le crée avec `np.array()`.

In [7]:
temperatures_tab = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
print(temperatures_tab)

[24.5 25.1 26.3 27.  25.8]


### 3) Multiplier par 2 les deux collections

* **Liste**

In [8]:
multiplication_list = temperatures_list * 2
print(multiplication_list)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]


* **tableau**

In [9]:
multiplication_tab = temperatures_tab * 2
print(multiplication_tab)

[49.  50.2 52.6 54.  51.6]


### 4) Quelle différence observe-t-on ?


**Explication :**

* Avec une **liste Python**, l'opérateur `* 2` ne multiplie pas les valeurs. Il **répète simplement la liste deux fois**, ce qui fait passer le nombre d'éléments de 5 à 10.
* Avec un **tableau NumPy**, l'opérateur `* 2` effectue une véritable multiplication : **chaque élément du tableau est multiplié par 2**, tout en conservant les 5 éléments.

Cette différence montre l'intérêt des tableaux NumPy pour les calculs numériques. NumPy permet d'effectuer des opérations **élément par élément**, sans avoir besoin d'utiliser une boucle `for`. On parle alors d'**opérations vectorisées**. Cette approche rend le code plus simple et plus adapté à la manipulation de grandes quantités de données, comme les mesures provenant de capteurs.



## Partie 2 : Création des données


**Objectif** 

Avant de pouvoir analyser des données de capteurs, il faut savoir créer des tableaux de différentes façons : tableaux vides à remplir plus tard, tableaux avec une valeur par défaut, tableaux de temps, ou données aléatoires pour simuler des mesures. 
NumPy propose des fonctions toutes prêtes pour chaque cas.


### 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [5]:
capteurs_zero = np.zeros(10)
print(capteurs_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


`np.zeros(n)` crée un tableau de `n` valeurs, toutes égales à 0

### 2) Créer un tableau contenant 10 valeurs égales à 1. 

In [6]:
capteurs_un = np.ones(10)
print(capteurs_un)  

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


`np.ones(n)` fonctionne comme `np.zeros`, mais remplit avec des 1 au lieu de des 0.

### 3) Créer un tableau de 10 valeurs initialisées à 25. 

In [7]:
capteurs_25= np.full(10, 25)
print(capteurs_25)

[25 25 25 25 25 25 25 25 25 25]


`np.full(n, valeur)` crée un tableau de `n` éléments, tous égaux à `valeur`.

### 4) Créer une matrice identité de taille 5 × 5. 

In [8]:
matrice_identite = np.eye(5)
print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


La **matrice identité** est une matrice carrée avec des 1 sur la diagonale et des 0 partout ailleurs. 

 `np.eye(n)` la génère directement.

### 5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [9]:
heures = np.arange(0, 24, 1)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


`np.arange(debut, fin)` génère une suite de nombres entiers, comme `range()` en Python classique, mais sous forme de tableau NumPy. Attention : la borne de fin (`24`) n'est **pas incluse**, donc on écrit `np.arange(0, 24)` pour obtenir les valeurs de 0 à 23.

### 6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C  

In [10]:
temperatures= np.linspace(20, 30, 10)
print(temperatures)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


`np.linspace(debut, fin, nombre_de_valeurs)` crée des valeurs **régulièrement espacées** entre deux bornes. Contrairement à `arange`, ici les deux bornes (20 et 30) **sont incluses**, et on précise directement combien de valeurs on veut au total.

### 7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

Pour générer des nombres aléatoires, on utilise `np.random`. Mais si on relance le code, on obtiendrait normalement des valeurs différentes à chaque fois !

Pour rendre les résultats **reproductibles** (les mêmes valeurs "aléatoires" à chaque exécution), on fixe une **graine aléatoire** avec `np.random.seed(un_nombre)` juste avant de générer les valeurs.

On utilise ensuite `np.random.uniform(min, max, taille)` pour générer des températures réalistes dans une plage donnée.

In [26]:
np.random.seed(42)
mesures_aleatoires = np.random.uniform(20, 60, 100).round(2)
print(mesures_aleatoires)

[34.98 58.03 49.28 43.95 26.24 26.24 22.32 54.65 44.04 48.32 20.82 58.8
 53.3  28.49 27.27 27.34 32.17 40.99 37.28 31.65 44.47 25.58 31.69 34.65
 38.24 51.41 27.99 40.57 43.7  21.86 44.3  26.82 22.6  57.96 58.63 52.34
 32.18 23.91 47.37 37.61 24.88 39.81 21.38 56.37 30.35 46.5  32.47 40.8
 41.87 27.39 58.78 51.01 57.58 55.79 43.92 56.87 23.54 27.84 21.81 33.01
 35.55 30.85 53.15 34.27 31.24 41.71 25.64 52.09 22.98 59.48 50.89 27.95
 20.22 52.62 48.27 49.16 50.85 22.96 34.34 24.63 54.52 44.93 33.24 22.54
 32.44 33.01 49.18 45.5  55.49 38.89 24.78 48.53 50.43 42.45 50.84 39.75
 40.91 37.1  21.02 24.32]


## Partie 3 – Exploration des tableaux 

**Objectif**

 Avant de manipuler un tableau, il est important de savoir "l'interroger" : combien de dimensions a-t-il, combien de valeurs contient-il, de quel type sont ces valeurs, et quelle est sa forme (nombre de lignes/colonnes). Ce sont des réflexes à avoir systématiquement, surtout quand on récupère des données dont on ne connaît pas encore la structure exacte.

### 1) Créer aléatoirement un tableau représentant les 24 températures d'une journée : 

In [28]:
np.random.seed(42)
temp_jour = np.random.uniform(18, 38, 24).round(2)
print(temp_jour)

[25.49 37.01 32.64 29.97 21.12 21.12 19.16 35.32 30.02 32.16 18.41 37.4
 34.65 22.25 21.64 21.67 24.08 28.5  26.64 23.82 30.24 20.79 23.84 25.33]


### 2) Déterminer les propriétés du tableau

Chaque tableau NumPy possède des **attributs** qui décrivent sa structure.On y accède sans parenthèses (ce ne sont pas des fonctions à appeler, mais des informations déjà stockées) :

- `.ndim` : nombre de **dimensions** (1 pour une simple liste de valeurs, 2 pour une matrice, etc.)
- `.size` : nombre total de valeurs dans le tableau
- `.dtype` : type des données stockées (ex: `float64` pour des nombres décimaux)
- `.shape` : la forme du tableau, sous forme de tuple (ex: `(24,)` pour 24 valeurs en 1 dimension)

In [30]:
# a) nombre de dimensions
print("Nombre de dimensions :", temp_jour.ndim)
# b) nombre de valeurs
print("Nombre de valeurs :", temp_jour.size)
# c) type des données
print("Type des données :", temp_jour.dtype)
# d) forme du tableau
print("Type des données :", temp_jour.shape)


Nombre de dimensions : 1
Nombre de valeurs : 24
Type des données : float64
Type des données : (24,)


### Partie 4 – Indexation et slicing 

**Objectif**
 Une fois qu'on a un tableau, on a presque toujours besoin d'en extraire une valeur précise ou une portion. En Python (et donc en NumPy), **le premier élément est à l'index 0**, pas 1. On va utiliser le tableau `temp_jour` créé en Partie 3 (les 24 températures d'une journée, aux heures 0 à 23).

### 1) la première mesure :

On accède à un élément avec des crochets `[index]`. Le premier élément est à l'index `0`.

In [31]:
print(temp_jour[0])  

25.49


### 2) la dernière mesure :

L'index `-1` désigne toujours le **dernier élément**, `-2` l'avant-dernier, etc. Très pratique pour ne pas avoir à compter le nombre exact d'éléments. 

In [32]:
print(temp_jour[-1]) 
 

25.33


### 3) la température de 8h :

Comme les heures vont de 0 à 23 et que l'index 0 correspond à l'heure 0, **l'heure et l'index coïncident directement** : l'heure 8h est à l'index `8`.

In [33]:
print(temp_jour[8])

30.02


### 4) les températures de 8h à 12h :

C'est le **slicing** ("découpage") : `tableau[debut:fin]` extrait une partie du tableau. Attention, la borne de fin est **exclue** : pour aller jusqu'à 12h inclus, il faut écrire `13` comme borne de fin.

In [35]:
print(temp_jour[8:13])

[30.02 32.16 18.41 37.4  34.65]


### 5) les températures des 6 premières heures :

Quand on omet le `debut` dans un slice, Python part automatiquement du tout début du tableau : `[:6]` équivaut à `[0:6]`.

In [36]:
print(temp_jour[:6])

[25.49 37.01 32.64 29.97 21.12 21.12]


### 6) les températures des heures paires

Le slicing accepte un **3e paramètre**, le pas (`step`) : `tableau[debut:fin:pas]`. Ici on veut les heures 0, 2, 4, 6... donc on part de 0 avec un pas de 2. En laissant `fin` vide, ça va jusqu'au bout du tableau.

In [37]:
print(temp_jour[0::2])

[25.49 32.64 21.12 19.16 30.02 18.41 34.65 21.64 24.08 26.64 30.24 23.84]
