# Atelier NumPy 

**Contexte :** Une entreprise dispose de capteurs installés dans plusieurs bâtiments. Ces capteurs mesurent la température, l'humidité, la pression et la consommation énergétique. On va préparer et analyser ces données avec NumPy, avant qu'elles soient utilisées par un futur système de Machine Learning.

Chaque partie contient :
- une **explication** en français simple,
- le **code** à exécuter,
- parfois une **question de réflexion**.

On commence par importer NumPy.
C'est la bibliothèque Python spécialisée dans le calcul scientifique et les tableaux de nombres . on l'utilise presque toujours avec le surnom `np`.

In [3]:
import numpy as np

---
## Partie 1 : Listes Python vs tableaux NumPy

**Objectif:**

 Avant d'utiliser NumPy, il faut comprendre *pourquoi* on l'utilise plutôt que les listes Python classiques. Les deux permettent de stocker plusieurs valeurs, mais elles ne se comportent pas du tout pareil face aux opérations mathématiques.

On dispose des températures mesurées par un capteur : `24.5, 25.1, 26.3, 27.0, 25.8`

### 1) Créer une liste Python stockant ces températures

Une **liste Python** est une structure générique : elle peut contenir n'importe quel type de données mélangées (nombres, texte, etc.). On la crée avec des crochets `[ ]`.

In [6]:
temperatures_list = [24.5, 25.1, 26.3, 27.0, 25.8 ]
print(temperatures_list)

[24.5, 25.1, 26.3, 27.0, 25.8]


### 2) Créer un tableau NumPy équivalent

Un **tableau NumPy** (`ndarray`) est optimisé pour les calculs numériques : toutes les valeurs sont du même type, stockées de façon compacte en mémoire, ce qui rend les calculs beaucoup plus rapides. On le crée avec `np.array()`.

In [7]:
temperatures_tab = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
print(temperatures_tab)

[24.5 25.1 26.3 27.  25.8]


### 3) Multiplier par 2 les deux collections

* **Liste**

In [8]:
multiplication_list = temperatures_list * 2
print(multiplication_list)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]


* **tableau**

In [9]:
multiplication_tab = temperatures_tab * 2
print(multiplication_tab)

[49.  50.2 52.6 54.  51.6]


### 4) Quelle différence observe-t-on ?


**Explication :**

* Avec une **liste Python**, l'opérateur `* 2` ne multiplie pas les valeurs. Il **répète simplement la liste deux fois**, ce qui fait passer le nombre d'éléments de 5 à 10.
* Avec un **tableau NumPy**, l'opérateur `* 2` effectue une véritable multiplication : **chaque élément du tableau est multiplié par 2**, tout en conservant les 5 éléments.

Cette différence montre l'intérêt des tableaux NumPy pour les calculs numériques. NumPy permet d'effectuer des opérations **élément par élément**, sans avoir besoin d'utiliser une boucle `for`. On parle alors d'**opérations vectorisées**. Cette approche rend le code plus simple et plus adapté à la manipulation de grandes quantités de données, comme les mesures provenant de capteurs.



## Partie 2 : Création des données


**Objectif** 

Avant de pouvoir analyser des données de capteurs, il faut savoir créer des tableaux de différentes façons : tableaux vides à remplir plus tard, tableaux avec une valeur par défaut, tableaux de temps, ou données aléatoires pour simuler des mesures. 
NumPy propose des fonctions toutes prêtes pour chaque cas.


### 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [5]:
capteurs_zero = np.zeros(10)
print(capteurs_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


`np.zeros(n)` crée un tableau de `n` valeurs, toutes égales à 0

### 2) Créer un tableau contenant 10 valeurs égales à 1. 

In [6]:
capteurs_un = np.ones(10)
print(capteurs_un)  

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


`np.ones(n)` fonctionne comme `np.zeros`, mais remplit avec des 1 au lieu de des 0.

### 3) Créer un tableau de 10 valeurs initialisées à 25. 

In [7]:
capteurs_25= np.full(10, 25)
print(capteurs_25)

[25 25 25 25 25 25 25 25 25 25]


`np.full(n, valeur)` crée un tableau de `n` éléments, tous égaux à `valeur`.

### 4) Créer une matrice identité de taille 5 × 5. 

In [8]:
matrice_identite = np.eye(5)
print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


La **matrice identité** est une matrice carrée avec des 1 sur la diagonale et des 0 partout ailleurs. 

 `np.eye(n)` la génère directement.

### 5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [9]:
heures = np.arange(0, 24, 1)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


`np.arange(debut, fin)` génère une suite de nombres entiers, comme `range()` en Python classique, mais sous forme de tableau NumPy. Attention : la borne de fin (`24`) n'est **pas incluse**, donc on écrit `np.arange(0, 24)` pour obtenir les valeurs de 0 à 23.

### 6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C  

In [10]:
temperatures= np.linspace(20, 30, 10)
print(temperatures)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


`np.linspace(debut, fin, nombre_de_valeurs)` crée des valeurs **régulièrement espacées** entre deux bornes. Contrairement à `arange`, ici les deux bornes (20 et 30) **sont incluses**, et on précise directement combien de valeurs on veut au total.

### 7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

Pour générer des nombres aléatoires, on utilise `np.random`. Mais si on relance le code, on obtiendrait normalement des valeurs différentes à chaque fois !

Pour rendre les résultats **reproductibles** (les mêmes valeurs "aléatoires" à chaque exécution), on fixe une **graine aléatoire** avec `np.random.seed(un_nombre)` juste avant de générer les valeurs.

On utilise ensuite `np.random.uniform(min, max, taille)` pour générer des températures réalistes dans une plage donnée.

In [26]:
np.random.seed(42)
mesures_aleatoires = np.random.uniform(20, 60, 100).round(2)
print(mesures_aleatoires)

[34.98 58.03 49.28 43.95 26.24 26.24 22.32 54.65 44.04 48.32 20.82 58.8
 53.3  28.49 27.27 27.34 32.17 40.99 37.28 31.65 44.47 25.58 31.69 34.65
 38.24 51.41 27.99 40.57 43.7  21.86 44.3  26.82 22.6  57.96 58.63 52.34
 32.18 23.91 47.37 37.61 24.88 39.81 21.38 56.37 30.35 46.5  32.47 40.8
 41.87 27.39 58.78 51.01 57.58 55.79 43.92 56.87 23.54 27.84 21.81 33.01
 35.55 30.85 53.15 34.27 31.24 41.71 25.64 52.09 22.98 59.48 50.89 27.95
 20.22 52.62 48.27 49.16 50.85 22.96 34.34 24.63 54.52 44.93 33.24 22.54
 32.44 33.01 49.18 45.5  55.49 38.89 24.78 48.53 50.43 42.45 50.84 39.75
 40.91 37.1  21.02 24.32]


## Partie 3 – Exploration des tableaux 

**Objectif**

 Avant de manipuler un tableau, il est important de savoir "l'interroger" : combien de dimensions a-t-il, combien de valeurs contient-il, de quel type sont ces valeurs, et quelle est sa forme (nombre de lignes/colonnes). Ce sont des réflexes à avoir systématiquement, surtout quand on récupère des données dont on ne connaît pas encore la structure exacte.

### 1) Créer aléatoirement un tableau représentant les 24 températures d'une journée : 

In [4]:
np.random.seed(42)
temp_jour = np.random.uniform(18, 38, 24).round(2)
print(temp_jour)

[25.49 37.01 32.64 29.97 21.12 21.12 19.16 35.32 30.02 32.16 18.41 37.4
 34.65 22.25 21.64 21.67 24.08 28.5  26.64 23.82 30.24 20.79 23.84 25.33]


### 2) Déterminer les propriétés du tableau

Chaque tableau NumPy possède des **attributs** qui décrivent sa structure.On y accède sans parenthèses (ce ne sont pas des fonctions à appeler, mais des informations déjà stockées) :

- `.ndim` : nombre de **dimensions** (1 pour une simple liste de valeurs, 2 pour une matrice, etc.)
- `.size` : nombre total de valeurs dans le tableau
- `.dtype` : type des données stockées (ex: `float64` pour des nombres décimaux)
- `.shape` : la forme du tableau, sous forme de tuple (ex: `(24,)` pour 24 valeurs en 1 dimension)

In [30]:
# a) nombre de dimensions
print("Nombre de dimensions :", temp_jour.ndim)
# b) nombre de valeurs
print("Nombre de valeurs :", temp_jour.size)
# c) type des données
print("Type des données :", temp_jour.dtype)
# d) forme du tableau
print("Type des données :", temp_jour.shape)


Nombre de dimensions : 1
Nombre de valeurs : 24
Type des données : float64
Type des données : (24,)


### Partie 4 – Indexation et slicing 

**Objectif**
 Une fois qu'on a un tableau, on a presque toujours besoin d'en extraire une valeur précise ou une portion. En Python (et donc en NumPy), **le premier élément est à l'index 0**, pas 1. On va utiliser le tableau `temp_jour` créé en Partie 3 (les 24 températures d'une journée, aux heures 0 à 23).

### 1) la première mesure :

On accède à un élément avec des crochets `[index]`. Le premier élément est à l'index `0`.

In [31]:
print(temp_jour[0])  

25.49


### 2) la dernière mesure :

L'index `-1` désigne toujours le **dernier élément**, `-2` l'avant-dernier, etc. Très pratique pour ne pas avoir à compter le nombre exact d'éléments. 

In [32]:
print(temp_jour[-1]) 
 

25.33


### 3) la température de 8h :

Comme les heures vont de 0 à 23 et que l'index 0 correspond à l'heure 0, **l'heure et l'index coïncident directement** : l'heure 8h est à l'index `8`.

In [33]:
print(temp_jour[8])

30.02


### 4) les températures de 8h à 12h :

C'est le **slicing** ("découpage") : `tableau[debut:fin]` extrait une partie du tableau. Attention, la borne de fin est **exclue** : pour aller jusqu'à 12h inclus, il faut écrire `13` comme borne de fin.

In [35]:
print(temp_jour[8:13])

[30.02 32.16 18.41 37.4  34.65]


### 5) les températures des 6 premières heures :

Quand on omet le `debut` dans un slice, Python part automatiquement du tout début du tableau : `[:6]` équivaut à `[0:6]`.

In [36]:
print(temp_jour[:6])

[25.49 37.01 32.64 29.97 21.12 21.12]


### 6) les températures des heures paires

Le slicing accepte un **3e paramètre**, le pas (`step`) : `tableau[debut:fin:pas]`. Ici on veut les heures 0, 2, 4, 6... donc on part de 0 avec un pas de 2. En laissant `fin` vide, ça va jusqu'au bout du tableau.

In [37]:
print(temp_jour[0::2])

[25.49 32.64 21.12 19.16 30.02 18.41 34.65 21.64 24.08 26.64 30.24 23.84]


## Partie 5 – Filtrage booléen

Jusqu'ici on choisissait des valeurs par leur position (index). Le filtrage booléen permet de choisir des valeurs **selon une condition** — exactement ce dont on a besoin pour détecter des anomalies dans les mesures de capteurs, sans savoir à l'avance à quel index elles se trouvent.

### 1) Afficher les températures supérieures à 30 °C 

In [38]:
print(temp_jour[temp_jour > 30])


[37.01 32.64 35.32 30.02 32.16 37.4  34.65 30.24]


### 2) Températures « normales » (entre 20°C et 30°C)

On peut combiner plusieurs conditions avec `&` (ET logique). **Important :** en NumPy, chaque condition doit être **entre parenthèses**, et on utilise `&`.

In [39]:
normales = temp_jour[(temp_jour >= 20) & (temp_jour <= 30)]
print(normales)

[25.49 29.97 21.12 21.12 22.25 21.64 21.67 24.08 28.5  26.64 23.82 20.79
 23.84 25.33]


### 3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. Déterminer anomalies, un tableau de booléen précisant les anomalies 

Ici on ne filtre pas directement : on **stocke** le résultat de la comparaison dans une variable. `anomalies` sera un tableau de `True`/`False`, de la même taille que `temp_jour`, indiquant pour chaque heure si la température est anormale.

In [40]:
anomalies = temp_jour > 35
print(anomalies)

[False  True False False False False False  True False False False  True
 False False False False False False False False False False False False]


### 4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies  

En Python, `True` est associé à la valeur `1` et `False` à la valeur `0`. Ainsi, lorsque l’on utilise `np.sum()` sur un tableau de valeurs booléennes, la fonction compte automatiquement le nombre de `True`. Cela permet donc de déterminer directement le nombre d’anomalies détectées.


In [41]:
nombre_anomalies = np.sum(anomalies)
print("Nombre d'anomalies :", nombre_anomalies)

Nombre d'anomalies : 3


## Partie6: Manipulation des dimensions 

On suppose qu’on a 5 capteurs. 

Jusqu'ici on travaillait avec un seul capteur (tableau à 1 dimension). Une entreprise a en réalité **plusieurs capteurs** : on a donc besoin de tableaux à 2 dimensions (des **matrices**), où chaque ligne peut représenter un capteur et chaque colonne une heure de la journée (ou l'inverse, selon comment on organise les données).
 ### 1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant une journée 

On utilise à nouveau `np.random.uniform`, mais cette fois le 3e argument est un **tuple** `(5, 24)` : 5 lignes (les capteurs) et 24 colonnes (les heures). On obtient directement une matrice à 2 dimensions.
e `.round(2)` c'est pour prendre 2 chiffres aprés la virgule

In [7]:
np.random.seed(42)
matrice_5capteurs = np.random.uniform(20, 50, (5, 24)).round(2)
print(matrice_5capteurs)


[[31.24 48.52 41.96 37.96 24.68 24.68 21.74 45.99 38.03 41.24 20.62 49.1
  44.97 26.37 25.45 25.5  29.13 35.74 32.96 28.74 38.36 24.18 28.76 30.99]
 [33.68 43.56 25.99 35.43 37.77 21.39 38.23 25.12 21.95 48.47 48.97 44.25
  29.14 22.93 40.53 33.2  23.66 34.86 21.03 47.28 27.76 39.88 29.35 35.6 ]
 [36.4  25.55 49.09 43.25 48.18 46.84 37.94 47.66 22.65 25.88 21.36 29.76
  31.66 28.14 44.86 30.7  28.43 36.28 24.23 44.07 22.24 49.61 43.17 25.96]
 [20.17 44.46 41.21 41.87 43.14 22.22 30.75 23.48 45.89 38.7  29.93 21.91
  29.33 29.76 41.89 39.13 46.62 34.17 23.59 41.4  42.82 36.84 43.13 34.81]
 [35.68 32.83 20.76 23.24 20.94 39.09 29.43 35.26 47.23 27.48 32.31 42.67
  26.86 22.31 28.69 24.84 47.89 44.24 39.   46.14 44.11 25.6  46.78 36.18]]


### 2) Transformer la matrice en un tableau unidimensionnel 

`.flatten()` "aplatit" une matrice : toutes les lignes sont mises bout à bout pour former un seul grand tableau à 1 dimension. Ici on obtiendra 5 × 24 = 120 valeurs.

In [43]:
matrice_unidi = matrice_5capteurs.flatten()
print(matrice_unidi)
print("Forme :", matrice_unidi.shape)

[32.51066014 41.6097348  20.00343124 29.06997718 24.40267672 22.77015784
 25.58780634 30.36682181 31.90302423 36.16450202 32.57583543 40.55658501
 26.13356749 46.34352309 20.8216278  40.11402531 32.51914407 36.76069485
 24.21160816 25.94304467 44.02233706 49.04784727 29.40272534 40.76967847
 46.29167457 46.83819991 22.55132634 21.1716435  25.09491259 46.3442751
 22.95040501 32.63322875 48.7366859  35.99495855 40.75631342 29.46546893
 40.59502783 45.03877016 20.54864832 42.50432945 49.66583267 42.44496963
 28.41331976 43.67837985 23.0967802  33.43680579 47.25786509 28.80842445
 28.63326016 23.90085716 20.58100874 40.36506599 26.34884348 27.96639978
 34.74719478 21.60087635 37.22352816 24.40185725 37.67916611 40.9927508
 23.07003286 32.42167963 40.83200473 32.42537809 21.49860377 36.07689218
 39.91383936 35.44667336 48.33784268 37.59665122 47.10205746 24.12424112
 24.17829042 44.22173866 31.93030511 24.96062591 47.82525741 30.43297579
 42.52436309 41.77993956 46.49918274 38.71016621 42.5

### 3) Déterminer la transposée de la matrice 

La **transposée** (`.T`) inverse les lignes et les colonnes : une matrice (5 capteurs, 24 heures) devient une matrice (24 heures, 5 capteurs). Utile pour changer de point de vue sur les mêmes données, selon ce qu'on veut analyser.

In [8]:
matrice_5capteurs_transpose = matrice_5capteurs.T
print(matrice_5capteurs_transpose)


[[31.24 33.68 36.4  20.17 35.68]
 [48.52 43.56 25.55 44.46 32.83]
 [41.96 25.99 49.09 41.21 20.76]
 [37.96 35.43 43.25 41.87 23.24]
 [24.68 37.77 48.18 43.14 20.94]
 [24.68 21.39 46.84 22.22 39.09]
 [21.74 38.23 37.94 30.75 29.43]
 [45.99 25.12 47.66 23.48 35.26]
 [38.03 21.95 22.65 45.89 47.23]
 [41.24 48.47 25.88 38.7  27.48]
 [20.62 48.97 21.36 29.93 32.31]
 [49.1  44.25 29.76 21.91 42.67]
 [44.97 29.14 31.66 29.33 26.86]
 [26.37 22.93 28.14 29.76 22.31]
 [25.45 40.53 44.86 41.89 28.69]
 [25.5  33.2  30.7  39.13 24.84]
 [29.13 23.66 28.43 46.62 47.89]
 [35.74 34.86 36.28 34.17 44.24]
 [32.96 21.03 24.23 23.59 39.  ]
 [28.74 47.28 44.07 41.4  46.14]
 [38.36 27.76 22.24 42.82 44.11]
 [24.18 39.88 49.61 36.84 25.6 ]
 [28.76 29.35 43.17 43.13 46.78]
 [30.99 35.6  25.96 34.81 36.18]]


### 4) Extraire toutes les mesures du capteur 1 

ans notre matrice, chaque **ligne** correspond à un capteur. Le "capteur 1" (au sens humain, le premier) correspond donc à l'**index 0**. `matrice[0]` (ou `matrice[0, :]`) sélectionne toute la première ligne.

In [9]:
capteur_1 = matrice_5capteurs[0, :]
print(capteur_1)

[31.24 48.52 41.96 37.96 24.68 24.68 21.74 45.99 38.03 41.24 20.62 49.1
 44.97 26.37 25.45 25.5  29.13 35.74 32.96 28.74 38.36 24.18 28.76 30.99]


### 5) Extraire toutes les mesures du capteur 5 

Le "capteur 5" (5e capteur) correspond à l'index `4` (puisqu'on compte à partir de 0). On peut aussi utiliser l'index `-1` puisque c'est le dernier capteur ici.

In [10]:
capteur_5 = matrice_5capteurs[4, :]
print(capteur_5)

[35.68 32.83 20.76 23.24 20.94 39.09 29.43 35.26 47.23 27.48 32.31 42.67
 26.86 22.31 28.69 24.84 47.89 44.24 39.   46.14 44.11 25.6  46.78 36.18]


### 6) Extraire les mesures de tous les capteurs à 10h 

Cette fois on veut une **colonne** entière (l'heure 10h pour tous les capteurs), pas une ligne. `matrice[:, 10]` signifie "toutes les lignes, colonne d'index 10".

In [11]:
mesures_10h = matrice_5capteurs[:, 10]
print(mesures_10h)

[20.62 48.97 21.36 29.93 32.31]


### 7) Extraire les mesures des capteurs 2 à 4 entre 8h et 12h

On combine deux slices à la fois : `matrice[lignes, colonnes]`. Les capteurs 2 à 4 correspondent aux index `1` à `3` inclus, donc le slice `1:4` (fin exclue). Les heures 8h à 12h inclus correspondent au slice `8:13`.

In [12]:
extrait = matrice_5capteurs[1:4, 8:13]
print(extrait)

[[21.95 48.47 48.97 44.25 29.14]
 [22.65 25.88 21.36 29.76 31.66]
 [45.89 38.7  29.93 21.91 29.33]]


##### **À retenir de cette partie :** pour une matrice, l'indexation se fait toujours sous la forme `matrice[lignes, colonnes]`. Le symbole `:` seul signifie "toutes les valeurs de cette dimension". C'est la base pour naviguer dans des données multi-capteurs.

## Partie 7 – Concaténation 

On suppose qu’on a un 2nd bâtiment avec 3 capteurs.  

### 1) Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs durant une journée 

In [13]:
np.random.seed(2)
matrice_batiment2 = np.random.uniform(15, 50, (3, 24))
print(matrice_batiment2)

[[30.25982157 15.90741811 34.23818673 30.23628374 29.71287307 26.56171874
  22.16270219 36.67448382 25.48791358 24.33895463 36.73968415 33.5199733
  19.71029809 32.97523424 21.4553953  42.48673017 44.88913524 32.29828931
  44.62965199 17.7875917  32.68361315 17.28502765 29.98428147 18.37858205]
 [19.45059901 35.88608581 22.91042002 18.74309895 22.71071725 27.24391998
  31.37256196 22.06101292 37.41423538 31.90744424 32.6832852  28.54124279
  42.77731091 35.30014626 20.68045095 39.52633213 48.7592878  32.50029264
  46.13320224 26.95647784 34.85004447 29.96410872 30.28615421 42.17957147]
 [33.74614607 48.38097794 34.04728561 17.87332228 27.82198406 44.77976764
  29.21962651 15.95208281 23.65120336 17.35005298 49.7848204  48.97031097
  43.00904229 36.06359925 41.77359512 20.92289063 25.25581311 33.34234064
  27.48184984 16.59876378 49.41037059 30.44742218 32.64001538 26.32394611]]


### 2) Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par les 8 capteurs durant une journée 

In [16]:
matrice_8capteurs = np.concatenate((matrice_5capteurs, matrice_batiment2), axis=0)
print(matrice_8capteurs.shape)

(8, 24)


## Partie 8 : Calcul scientifique 

**Pourquoi cette partie ?** NumPy fournit des fonctions statistiques prêtes à l'emploi (au lieu de les recalculer à la main). On les utilise pour résumer et transformer les données de température du 1er bâtiment, avant de les transmettre à un système de Machine Learning — la standardisation et la normalisation sont des étapes très courantes en préparation de données.

### 1) Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la variance et l’écart-type 

In [5]:

print("Min :", temp_jour.min())
print("Max :", temp_jour.max())
print("Somme :", temp_jour.sum())
print("Moyenne :", temp_jour.mean())
print("Médiane :", np.median(temp_jour))
print("Variance :", temp_jour.var())
print("Écart-type :", temp_jour.std())

Min : 18.41
Max : 37.4
Somme : 643.27
Moyenne : 26.802916666666665
Médiane : 25.409999999999997
Variance : 32.532812326388886
Écart-type : 5.703754230889413


### 2) Standardiser le tableau des températures puis vérifier les valeurs de la moyenne et de l’écarttype du tableau standardisé 

La **standardisation** transforme les données pour qu'elles aient une **moyenne de 0** et un **écart-type de 1**. Formule : `(valeur - moyenne) / écart-type`. Très utilisée en Machine Learning, car elle met toutes les variables "à la même échelle".

In [6]:
temperatures_standardisees = (temp_jour - temp_jour.mean()) / temp_jour.std()
print(temperatures_standardisees)
print("Nouvelle moyenne (≈ 0) :", temperatures_standardisees.mean())
print("Nouvel écart-type (≈ 1) :", temperatures_standardisees.std())

[-0.23018465  1.78953772  1.02337567  0.55526294 -0.99634669 -0.99634669
 -1.33998001  1.49324164  0.56402909  0.93922058 -1.47147235  1.85791374
  1.37577515 -0.79823157 -0.90517867 -0.89991898 -0.47739025  0.29753795
 -0.02856306 -0.52297426  0.60260018 -1.05420332 -0.5194678  -0.25823635]
Nouvelle moyenne (≈ 0) : 2.590520390792032e-16
Nouvel écart-type (≈ 1) : 1.0


### 3) Normaliser (Min-Max) le tableau des températures puis vérifier les valeurs du tableau normalisé 


La **normalisation Min-Max** ramène toutes les valeurs entre **0 et 1**. Formule : `(valeur - min) / (max - min)`. La valeur minimale du tableau devient 0, la valeur maximale devient 1, et les autres se répartissent proportionnellement entre les deux.

In [7]:
temperatures_normalisees = (temp_jour - temp_jour.min()) / (temp_jour.max() - temp_jour.min())
print(temperatures_normalisees)
print("Nouveau min (= 0) :", temperatures_normalisees.min())
print("Nouveau max (= 1) :", temperatures_normalisees.max())

[0.3728278  0.97946288 0.74934176 0.60874144 0.14270669 0.14270669
 0.03949447 0.89046867 0.61137441 0.7240653  0.         1.
 0.85518694 0.20221169 0.17008952 0.1716693  0.2985782  0.53133228
 0.43338599 0.28488678 0.62295945 0.12532912 0.28593997 0.36440232]
Nouveau min (= 0) : 0.0
Nouveau max (= 1) : 1.0


 ### 4) Convertir en Fahrenheit

Formule de conversion Celsius → Fahrenheit : `F = C × 9/5 + 32`. Grâce à la vectorisation NumPy (vue en Partie 1), on applique directement cette formule à tout le tableau, sans boucle.

In [9]:
temperatures_fahrenheit = temp_jour * 9/5 + 32
print(temperatures_fahrenheit)

[77.882 98.618 90.752 85.946 70.016 70.016 66.488 95.576 86.036 89.888
 65.138 99.32  94.37  72.05  70.952 71.006 75.344 83.3   79.952 74.876
 86.432 69.422 74.912 77.594]


## Partie 9 : Broadcasting 

Le **broadcasting** est un mécanisme de NumPy qui permet d'effectuer des opérations entre tableaux de tailles différentes, sans avoir à les rendre manuellement de la même taille. C'est extrêmement pratique pour appliquer une correction de calibration à plusieurs capteurs en une seule ligne.

### 1) Matrice `temperatures_3x3` : mesures à 10h, 11h et 12h dans le 2e bâtiment

Le 2e bâtiment a 3 capteurs, et on s'intéresse à 3 heures précises (10h, 11h, 12h). On organise la matrice avec **une ligne par heure** et **une colonne par capteur** : forme `(3 heures, 3 capteurs)`. C'est ce choix d'organisation (heures en lignes, capteurs en colonnes) qui va permettre au broadcasting de bien fonctionner à l'étape suivante.

In [10]:
np.random.seed(3)
temperatures_3x3 = np.random.uniform(15, 35, (3, 3))  # 3 heures (lignes) x 3 capteurs (colonnes)
print(temperatures_3x3)
print("Forme :", temperatures_3x3.shape)

[[26.01595805 29.16295645 20.81809478]
 [25.2165521  32.85893909 32.92586178]
 [17.51170621 19.14485756 16.02934407]]
Forme : (3, 3)


### 2) Appliquer la correction de calibration

`correction` est un tableau de 3 valeurs (une par capteur), alors que `temperatures_3x3` est une matrice `(3, 3)`. Normalement, additionner deux tableaux de tailles différentes devrait poser problème...

...mais grâce au **broadcasting**, NumPy comprend automatiquement que `correction` doit être appliqué **à chaque ligne** (donc à chaque heure), colonne par colonne — c'est-à-dire capteur par capteur. C'est comme si `correction` était "répété" 3 fois, une fois par ligne (par heure), sans qu'on ait besoin de l'écrire explicitement. Résultat : le capteur 1 (1ère colonne) reçoit toujours `+1`, le capteur 2 toujours `-0.5`, le capteur 3 toujours `+0.2`, et ce pour les 3 heures.

In [11]:
correction = np.array([1, -0.5, 0.2])
mesures_corrigees = temperatures_3x3 + correction
print(mesures_corrigees)

[[27.01595805 28.66295645 21.01809478]
 [26.2165521  32.35893909 33.12586178]
 [18.51170621 18.64485756 16.22934407]]


--
## Conclusion

Cet atelier a couvert les bases essentielles de NumPy pour l'analyse de données de capteurs IoT : création de tableaux, exploration, indexation/slicing, filtrage booléen, manipulation de dimensions, concaténation, calcul scientifique et broadcasting. Ces briques sont la base de toute préparation de données avant un système de Machine Learning.