# Atelier NumPy 

**Contexte :** Une entreprise dispose de capteurs installés dans plusieurs bâtiments. Ces capteurs mesurent la température, l'humidité, la pression et la consommation énergétique. On va préparer et analyser ces données avec NumPy, avant qu'elles soient utilisées par un futur système de Machine Learning.

Chaque partie contient :
- une **explication** en français simple,
- le **code** à exécuter,
- parfois une **question de réflexion**.

On commence par importer NumPy.
C'est la bibliothèque Python spécialisée dans le calcul scientifique et les tableaux de nombres . on l'utilise presque toujours avec le surnom `np`.

In [2]:
import numpy as np

---
## Partie 1 : Listes Python vs tableaux NumPy

**Pourquoi cette partie ?**

 Avant d'utiliser NumPy, il faut comprendre *pourquoi* on l'utilise plutôt que les listes Python classiques. Les deux permettent de stocker plusieurs valeurs, mais elles ne se comportent pas du tout pareil face aux opérations mathématiques.

On dispose des températures mesurées par un capteur : `24.5, 25.1, 26.3, 27.0, 25.8`

### 1) Créer une liste Python stockant ces températures

Une **liste Python** est une structure générique : elle peut contenir n'importe quel type de données mélangées (nombres, texte, etc.). On la crée avec des crochets `[ ]`.

In [6]:
temperatures_list = [24.5, 25.1, 26.3, 27.0, 25.8 ]
print(temperatures_list)

[24.5, 25.1, 26.3, 27.0, 25.8]


### 2) Créer un tableau NumPy équivalent

Un **tableau NumPy** (`ndarray`) est optimisé pour les calculs numériques : toutes les valeurs sont du même type, stockées de façon compacte en mémoire, ce qui rend les calculs beaucoup plus rapides. On le crée avec `np.array()`.

In [7]:
temperatures_tab = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
print(temperatures_tab)

[24.5 25.1 26.3 27.  25.8]


### 3) Multiplier par 2 les deux collections

* **Liste**

In [8]:
multiplication_list = temperatures_list * 2
print(multiplication_list)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]


* **tableau**

In [9]:
multiplication_tab = temperatures_tab * 2
print(multiplication_tab)

[49.  50.2 52.6 54.  51.6]


### 4) Quelle différence observe-t-on ?


**Explication :**

* Avec une **liste Python**, l'opérateur `* 2` ne multiplie pas les valeurs. Il **répète simplement la liste deux fois**, ce qui fait passer le nombre d'éléments de 5 à 10.
* Avec un **tableau NumPy**, l'opérateur `* 2` effectue une véritable multiplication : **chaque élément du tableau est multiplié par 2**, tout en conservant les 5 éléments.

Cette différence montre l'intérêt des tableaux NumPy pour les calculs numériques. NumPy permet d'effectuer des opérations **élément par élément**, sans avoir besoin d'utiliser une boucle `for`. On parle alors d'**opérations vectorisées**. Cette approche rend le code plus simple et plus adapté à la manipulation de grandes quantités de données, comme les mesures provenant de capteurs.



## Partie 2 : Création des données


**Objectif** 

Avant de pouvoir analyser des données de capteurs, il faut savoir créer des tableaux de différentes façons : tableaux vides à remplir plus tard, tableaux avec une valeur par défaut, tableaux de temps, ou données aléatoires pour simuler des mesures. 
NumPy propose des fonctions toutes prêtes pour chaque cas.


### 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [5]:
capteurs_zero = np.zeros(10)
print(capteurs_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


`np.zeros(n)` crée un tableau de `n` valeurs, toutes égales à 0

### 2) Créer un tableau contenant 10 valeurs égales à 1. 

In [6]:
capteurs_un = np.ones(10)
print(capteurs_un)  

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


`np.ones(n)` fonctionne comme `np.zeros`, mais remplit avec des 1 au lieu de des 0.

### 3) Créer un tableau de 10 valeurs initialisées à 25. 

In [7]:
capteurs_25= np.full(10, 25)
print(capteurs_25)

[25 25 25 25 25 25 25 25 25 25]


`np.full(n, valeur)` crée un tableau de `n` éléments, tous égaux à `valeur`.

### 4) Créer une matrice identité de taille 5 × 5. 

In [8]:
matrice_identite = np.eye(5)
print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


La **matrice identité** est une matrice carrée avec des 1 sur la diagonale et des 0 partout ailleurs. 

 `np.eye(n)` la génère directement.

### 5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [9]:
heures = np.arange(0, 24, 1)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


`np.arange(debut, fin)` génère une suite de nombres entiers, comme `range()` en Python classique, mais sous forme de tableau NumPy. Attention : la borne de fin (`24`) n'est **pas incluse**, donc on écrit `np.arange(0, 24)` pour obtenir les valeurs de 0 à 23.

### 6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C  

In [10]:
temperatures= np.linspace(20, 30, 10)
print(temperatures)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


`np.linspace(debut, fin, nombre_de_valeurs)` crée des valeurs **régulièrement espacées** entre deux bornes. Contrairement à `arange`, ici les deux bornes (20 et 30) **sont incluses**, et on précise directement combien de valeurs on veut au total.

### 7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

Pour générer des nombres aléatoires, on utilise `np.random`. Mais si on relance le code, on obtiendrait normalement des valeurs différentes à chaque fois !

Pour rendre les résultats **reproductibles** (les mêmes valeurs "aléatoires" à chaque exécution), on fixe une **graine aléatoire** avec `np.random.seed(un_nombre)` juste avant de générer les valeurs.

On utilise ensuite `np.random.uniform(min, max, taille)` pour générer des températures réalistes dans une plage donnée.

In [13]:
np.random.seed(42)
mesures_aleatoires = np.random.uniform(20, 60, 10)
print(mesures_aleatoires)

[34.98160475 58.02857226 49.27975767 43.94633937 26.24074562 26.23978081
 22.32334449 54.64704583 44.04460047 48.32290311]
